spin_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A Spin example HTTP application with components."
name = "spin-hello-rs"
trigger = { type = "http", base = "/" }
version = "1.0.0"


[[component]]
id = "rust-hello"
source = "rust-hello/target/wasm32-wasi/release/rust_hello.wasm"
[component.trigger]
# this component will be invoked for requests on route `/hello`
route = "/hello"
