[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime", features = ["component-model"] }
wit-component = "*"
